### ISSUE TITLE
Please add a licence file

### ISSUE THREAD

**Issue by Flying--Dutchman** [jocontacter/asceticcropper#10]
Without a license file, the use of this great plugin in a private or commercial app is legally not allowed.

**Comment by jocontacter** [comment]
Hi, if you attach appropriate license file, i will add it to plugin

**Comment by Flying--Dutchman** [comment]
I created a pull request with an MIT license file.
I hope that the MIT license suits you. Otherwise I can create another one 👍

**Comment by Flying--Dutchman** [comment]
Thank you very much :tada:
