### ISSUE TITLE
Horizontal rectangle doesn't work until resizing

### ISSUE THREAD

**Issue by ederjbezerra** [jocontacter/asceticcropper#2]
This plugin is amazing and it's the unique that worked nice and without errors, but when I use 

`cropper.MaskPainter = new RectangleMaskPainter() { CornerRadius = 10, Corners = CornersEnum.All, MaskHeight = 0.5, MaskWidth = 1 };`

and the loaded image for cropping is 1:1, the crop area is raised also as a square(1:1). It only will turn into a rectangle area if I resize to the minimum as I can, suddenly it becomes the expected rectangle. If I open a vertical image, it works at first shot.

 Does any one here have any idea of how to solve that?

**Comment by jocontacter** [comment]
"This plugin is amazing and it's the unique that worked nice and without errors, but when I use" - thank you.
i'll check this problem

**Comment by jocontacter** [comment]
> This plugin is amazing and it's the unique that worked nice and without errors, but when I use
> 
> `cropper.MaskPainter = new RectangleMaskPainter() { CornerRadius = 10, Corners = CornersEnum.All, MaskHeight = 0.5, MaskWidth = 1 };`
> 
> and the loaded image for cropping is 1:1, the crop area is raised also as a square(1:1). It only will turn into a rectangle area if I resize to the minimum as I can, suddenly it becomes the expected rectangle. If I open a vertical image, it works at first shot.
> 
> Does any one here have any idea of how to solve that?

what version do you have installed? 
can you tell me the size of your picture?

**Comment by ederjbezerra** [comment]
> > This plugin is amazing and it's the unique that worked nice and without errors, but when I use
> > `cropper.MaskPainter = new RectangleMaskPainter() { CornerRadius = 10, Corners = CornersEnum.All, MaskHeight = 0.5, MaskWidth = 1 };`
> > and the loaded image for cropping is 1:1, the crop area is raised also as a square(1:1). It only will turn into a rectangle area if I resize to the minimum as I can, suddenly it becomes the expected rectangle. If I open a vertical image, it works at first shot.
> > Does any one here have any idea of how to solve that?
> 
> what version do you have installed?
> can you tell me the size of your picture?
> Android or iOS?

Version 1.0.4 on Android.  Size: 800x800 px

**Comment by jocontacter** [comment]
Fixed in 1.0.5

**Comment by ederjbezerra** [comment]
> Fixed in 1.0.5

That's it! Thank you, now it works!
