### ISSUE TITLE
How can I set image from stream as PhotoSource of ImageCropperView?

### ISSUE THREAD

**Issue by kubaflo** [jocontacter/asceticcropper#3]
When I do:  `cropperPhotoSource = ImageSource.FromStream(() => CropImagePopup.imageToCut);` in the ViewModel it works (the image appears), however, every time when I want to execute `await cropper.GetImageAsJpegAsync(90, 200, 200);` I get System.NullReferenceException :/

**Comment by jocontacter** [comment]
i'll check it

**Comment by jocontacter** [comment]
> When I do: `cropperPhotoSource = ImageSource.FromStream(() => CropImagePopup.imageToCut);` in the ViewModel it works (the image appears), however, every time when I want to execute `await cropper.GetImageAsJpegAsync(90, 200, 200);` I get System.NullReferenceException :/

can you make repro?

**Comment by jocontacter** [comment]
I'm sure what your `imageToCut` is null in `cropperPhotoSource = ImageSource.FromStream(() => CropImagePopup.imageToCut);`
