### ISSUE TITLE
Want to bind ResultPhotoSource in more than one Image source

### ISSUE THREAD

**Issue by abraham891** [jocontacter/asceticcropper#5]
If ```ResultPhotoSource``` is binded to more than one image source, it throws ```ObjectDisposedException```, "Cannot access the closed stream".

Help would be appreciated.

**Comment by jocontacter** [comment]
Hi Abraham! ResultPhotoSource is not a part of asceticcropper. You can take the stream returned by `cropper.GetImageAsJpegAsync` and copy it as much. as you want)
