### ISSUE TITLE
Resize MaskPainter

### ISSUE THREAD

**Issue by Flying--Dutchman** [jocontacter/asceticcropper#8]
Hello, is it possible to reduce the size of the MaskPainter so that the user is able to pick a specific part of the image?

**Comment by jocontacter** [comment]
Hello. Why not?

Пт, 1 окт. 2021 г. в 12:29, Flying--Dutchman ***@***.***>:

**Comment by Flying--Dutchman** [comment]
Sorry, my bad. Problems with my Emulator on Mint.
Thank you :+1:
